### ISSUE TITLE
Support SQL related databases and the relevant data nodes

### ISSUE THREAD

**Issue by realstraw** [krux/hyperion#13] opened 2015-03-26 03:01 UTC
- http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-rdsdatabase.html
- http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-sqldatanode.html

**Comment by sethyates** [comment] 2015-03-26 03:03
Potential duplicate of #8

**Closed** 2015-03-29 08:47 UTC
Labels: duplicate, enhancement
